name = "b2-mirror"
main = "src/index.ts"
compatibility_date = "2023-11-21"

# Variable bindings. These are arbitrary, plaintext strings (similar to environment variables)
# Note: Use secrets to store sensitive data.
# Docs: https://developers.cloudflare.com/workers/platform/environment-variables
[vars]
B2_AUTH_ENDPOINT = "https://api.backblazeb2.com/b2api/v2/b2_authorize_account"
B2_BUCKET = "ylsink"
B2_BUCKET_ID = "f7ebbad5d0897308883a0917"
B2_DOMAIN = "f004.backblazeb2.com"
B2_KEY_ID = "0047ba509388a970000000001"
# B2_KEY is a secret.
